services:
  - type: web
    name: dsp391m-nhom8-ev-gasoline-tco
    runtime: python
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
